# Assignment-3
## UCS420 "Cognitive Computing"
## Pandas

## Q.1 Create a dataset as shown in the table.

In [1]:
import pandas as pd
import numpy as np

data = {
    "Refund": ["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital Status": ["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable Income": ["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat": ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}

df = pd.DataFrame(data, index=pd.RangeIndex(1, 11, name="Tid"))
df

    Refund Marital Status Taxable Income Cheat
Tid
1      Yes         Single           125K    No
2       No        Married           100K    No
3       No         Single            70K    No
4      Yes        Married           120K    No
5       No       Divorced            95K   Yes
6       No        Married            60K    No
7      Yes       Divorced           220K    No
8       No         Single            85K   Yes
9       No        Married            75K    No
10      No         Single            90K   Yes

## Q.2 Locate row 0, 4, 7 and 8 using DataFrame.
Since the DataFrame's index starts at `1` (Tid), we reset to a default 0-based index first so that positions 0, 4, 7, 8 correspond exactly to the requested rows, then use `.loc`.

In [2]:
df2 = df.reset_index()  # bring Tid back as a column, default 0-based index
df2.loc[[0, 4, 7, 8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q.3 Navigate the DataFrame

### 1. Select row from index 3 to 7 (using `df2`, 0-based index)

In [3]:
df2.loc[3:7]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

### 2. Select row from index 4 to 8, and column 2 to 4

In [4]:
df2.iloc[4:9, 2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

### 3. Select all rows with column index 1 to 3 (include index 3 during selection)

In [5]:
df2.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q.4 Read a CSV file and display its first five rows.
Dataset: [Iris dataset](https://www.kaggle.com/datasets/uciml/iris).

Place `Iris.csv` in the same folder as this notebook (downloaded from the Kaggle link above) and run the cell below. If the file isn't found, the cell automatically generates an equivalent `Iris.csv` locally so the notebook still runs end-to-end.

In [6]:
import os

if not os.path.exists("Iris.csv"):
    # Fallback: build an equivalent Iris.csv locally (same schema as the Kaggle version)
    from sklearn.datasets import load_iris
    iris = load_iris(as_frame=True)
    iris_df = iris.frame.copy()
    iris_df.columns = ["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm","target"]
    species_map = {0: "Iris-setosa", 1: "Iris-versicolor", 2: "Iris-virginica"}
    iris_df["Species"] = iris_df["target"].map(species_map)
    iris_df = iris_df.drop(columns=["target"])
    iris_df.insert(0, "Id", range(1, len(iris_df) + 1))
    iris_df.to_csv("Iris.csv", index=False)

iris_data = pd.read_csv("Iris.csv")
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Q.5 Delete row 4 and delete column 3 from the CSV loaded in Q.4. Display the result.

In [7]:
iris_modified = iris_data.drop(index=4)          # delete row with label 4
iris_modified = iris_modified.drop(iris_modified.columns[3], axis=1)  # delete column at position 3
iris_modified.head()

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

## Q.6 Create a sample dataset (`employees.csv`)

In [8]:
emp_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees = pd.DataFrame(emp_data)
employees["Joining_Date"] = pd.to_datetime(employees["Joining_Date"])
employees.to_csv("employees.csv", index=False)
employees

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### a) Shape (number of rows and columns) of the DataFrame

In [9]:
employees.shape

(5, 10)

### b) Summary of the DataFrame (data types and non-null counts)

In [10]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      datetime64[us]
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: datetime64[us](1), float64(1), int64(5), str(3)
memory usage: 532.0 bytes

### c) Descriptive statistics

In [11]:
employees.describe(include="all")

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
count,5.000000,5,5,5.000000,5.00000,5.000000,5,5,5.0,5.000000
unique,NaN,5,4,NaN,NaN,NaN,NaN,2,NaN,NaN
top,NaN,Alice,IT,NaN,NaN,NaN,NaN,Male,NaN,NaN
freq,NaN,1,2,NaN,NaN,NaN,NaN,3,NaN,NaN
mean,103.000000,NaN,NaN,34.000000,60000.00000,7.400000,2016-08-20 00:00:00,NaN,5500.0,4.100000
min,101.000000,NaN,NaN,28.000000,50000.00000,3.000000,2010-11-25 00:00:00,NaN,4500.0,3.500000
25%,102.000000,NaN,NaN,29.000000,55000.00000,4.000000,2013-06-01 00:00:00,NaN,5000.0,3.800000
50%,103.000000,NaN,NaN,34.000000,60000.00000,8.000000,2017-07-19 00:00:00,NaN,5000.0,4.000000
75%,104.000000,NaN,NaN,38.000000,65000.00000,10.000000,2020-03-15 00:00:00,NaN,6000.0,4.500000
max,105.000000,NaN,NaN,41.000000,70000.00000,12.000000,2021-02-10 00:00:00,NaN,7000.0,4.700000
std,1.581139,NaN,NaN,5.612486,7905.69415,3.847077,NaN,NaN,1000.0,0.494975

### d) First 5 rows and last 3 rows

In [12]:
employees.head(5)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [13]:
employees.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### e) Statistics

In [14]:
avg_salary = employees["Salary"].mean()
total_bonus = employees["Bonus"].sum()
youngest_age = employees["Age"].min()
highest_rating = employees["Rating"].max()

print("i.   Average salary:", avg_salary)
print("ii.  Total bonus paid:", total_bonus)
print("iii. Youngest employee's age:", youngest_age)
print("iv.  Highest performance rating:", highest_rating)

i.   Average salary: 60000.0
ii.  Total bonus paid: 27500
iii. Youngest employee's age: 28
iv.  Highest performance rating: 4.7

### f) Sort the DataFrame by Salary column in descending order

In [15]:
employees_sorted = employees.sort_values(by="Salary", ascending=False)
employees_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### g) Add a new column that categorizes employees based on performance rating

In [16]:
def rating_category(r):
    if r >= 4.5:
        return "Excellent"
    elif r >= 4.0:
        return "Good"
    else:
        return "Average"

employees["Performance_Category"] = employees["Rating"].apply(rating_category)
employees

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### h) Identify missing values in the DataFrame

In [17]:
employees.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### i) Rename the Employee_ID column to ID

In [18]:
employees = employees.rename(columns={"Employee_ID": "ID"})
employees.head()

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### j) Find all employees who:

**i. Have more than 5 years of experience**

In [19]:
employees[employees["Years_of_Experience"] > 5]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

**ii. Belong to the IT department**

In [20]:
employees[employees["Department"] == "IT"]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

### k) Add a new column `Tax` which deducts 10% of the Salary

In [21]:
employees["Tax"] = employees["Salary"] * 0.10
employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

### l) Save the modified DataFrame (with added columns) to a new CSV file

In [22]:
employees.to_csv("employees_modified.csv", index=False)
print("Saved to employees_modified.csv")

Saved to employees_modified.csv